### ISSUE TITLE
crash with charm

### ISSUE THREAD

**Issue by Ajw2003** [Harvest-Festival/Simply-Seasons#5]
attached is the crash report

I was playing with only simply seasons, charm, and its required dependencies. I tried this with serene seasons as well as without and still the same crash occurred

Playing on 1.16.5 version 36.1.65 also tried on 36.1.33 and the same issue occurred 

I'm not sure if this issue is best solved on your end or the charm dev teams but without simply seasons charm functions flawlessly and vice versa

[crash-2021-07-21_18.01.50-client.txt](https://github.com/Harvest-Festival/Simply-Seasons/files/6859326/crash-2021-07-21_18.01.50-client.txt)

**Comment by joshiejack** [comment]
update the mod... kinda funny you didn't try this. It's literally in the changelog. the issue is that in 1.0.12 i added a heavier snow texture for the blizzard. Charm also adds a heavier snow texture so it conflicts. I changed it to give mine less priority and let it fail. Technically crashing on their end cause they don't let their mixins fail but that's fine, idc if mine do.
